#!/usr/bin/python3

from sys import *
from collections import *

def extract_text(filename):
    with open(filename, 'r') as file:
        text = file.read().splitlines()

    return text

def extract_win_numbers(text):
    tab = defaultdict(int)

    for i, line in enumerate(text):
        line = line.split(": ")[1]
        wins, nums = map(str.split, line.split(" | "))
        scratchcards = sum(nums.count(w) for w in wins)
        print(tab)
        tab[i] += 1
        for j in range(i + 1, i + scratchcards + 1):
            tab[j] += tab[i]

    return tab.values()

def sum_scratchcards(tab):
    sum = 0

    for scratchcards in tab:
        sum += scratchcards

    return sum

def main():
    if (len(argv) != 2):
        print("\nWrong uttilisation of the program:\nTry: ./day_01_01 'txt filepath'\n")

    try:
        filename = argv[1]
    except:
        print("Wrong file or permission denied")

    text = extract_text(filename)
    tab = extract_win_numbers(text)
    sum = sum_scratchcards(tab)

    print("The sum of all scratchcards is :", sum)

main()