#!/usr/bin/python3

from sys import *

def extract_text(filename):
    with open(filename, 'r') as file:
        text = file.read().strip()

    return text

def sum_valid_races(time, dist):
    sum = 0

    for x in range(time + 1):
        distx = x * (time - x)

        if distx >= dist:
            sum += 1

    return sum

def get_time_dist(text):
    line1, line2 = text.split('\n')

    numbers_times = [int(x) for x in line1.split(':')[1].split()]
    numbers_dist = [int(x) for x in line2.split(':')[1].split()]

    time = dist = ''
    for t in numbers_times:
      time += str(t)
    time = int(time)
    for d in numbers_dist:
      dist += str(d)
    dist = int(dist)

    return time, dist

def main():
    if (len(argv) != 2):
        print("\nWrong uttilisation of the program:\nTry: ./day_01_01 'txt filepath'\n")

    try:
        text = extract_text(argv[1])
    except:
        print("Wrong file or permission denied")

    time, dist = get_time_dist(text)
    sum = sum_valid_races(time, dist)

    print("The sum of numbers of ways is:", sum)

main()