#!/usr/bin/python3

from sys import *

def extract_text(filename):
    with open(filename, 'r') as file:
        text = file.read().splitlines()

    return text

def is_symbol(text, height, width, i, j, num, gear_numbers):
    if not (0 <= i < height and 0 <= j < width):
        return False

    if text[i][j] == "*":
        gear_numbers[i][j].append(num)

    return text[i][j] != "." and not text[i][j].isdigit()

def get_gear_numbers(text):
    height = len(text)
    width = len(text[0])
    gear_numbers = [[[] for _ in range(width)] for _ in range(height)]
    tab = []

    for i, line in enumerate(text):
        start, j = 0, 0

        while j < width:
            start = j
            num = ""

            while j < width and line[j].isdigit():
                num += line[j]
                j += 1

            if num == "":
                j += 1
                continue

            num = int(num)

            is_symbol(text, height, width, i, start - 1, num, gear_numbers) or is_symbol(text, height, width, i, j, num, gear_numbers)

            for k in range(start - 1, j + 1):
                is_symbol(text, height, width, i - 1, k, num, gear_numbers) or is_symbol(text, height, width, i + 1, k, num, gear_numbers)

    for i in range(height):
        for j in range(width):
            nums = gear_numbers[i][j]

            if text[i][j] == "*" and len(nums) == 2:
                tab.append(nums[0] * nums[1])

    return tab

def sum_numbers(tab):
    sum = 0

    for number in tab:
        sum += number

    return sum

def main():
    if (len(argv) != 2):
        print("\nWrong uttilisation of the program:\nTry: ./day_01_01 'txt filepath'\n")

    try:
        filename = argv[1]
    except:
            print("Wrong file or permission denied")

    text = extract_text(filename)
    tab = get_gear_numbers(text)
    sum = sum_numbers(tab)

    print("The sum of all gear number is :", sum)

main()